# Generated by Django 6.0.4 on 2026-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
