# Generated by Django 6.0.4 on 2026-05-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0004_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
